name: LinceTech Academy - Orientacao a objetos 1
type: flutter
steps:
  - name: Atividade 1
    directory: ap_1
    has_solution: true
  - name: Atividade 2
    directory: ap_2
    has_solution: true
  - name: Atividade 3
    directory: ap_3
    has_solution: true
