name: LinceTech Academy - Dart - Operadores
type: dart
steps:
  - name: Atividade 1
    directory: ap_1
    has_solution: true
  - name: Atividade 2
    directory: ap_2
    has_solution: true
  - name: Atividade 3
    directory: ap_3
    has_solution: true
  - name: Atividade 4
    directory: ap_4
    has_solution: true
  - name: Atividade 5
    directory: ap_5
    has_solution: true