name: LinceTech Academy - Desafios Dart 2
type: dart
steps:
  - name: Desafio 1
    directory: de_1
    has_solution: false
  - name: Desafio 2
    directory: de_2
    has_solution: false
  - name: Desafio 3
    directory: de_3
    has_solution: false
  - name: Desafio 4
    directory: de_4
    has_solution: false
  - name: Desafio 5
    directory: de_5
    has_solution: false
  - name: Desafio 6
    directory: de_6
    has_solution: false
  - name: Desafio 7
    directory: de_7
    has_solution: false
  - name: Desafio 8
    directory: de_8
    has_solution: false
  - name: Desafio 9
    directory: de_9
    has_solution: false